config/routes.rb
Rails.application.routes.draw do
  # get 'dashboards/index'
  root 'foods#index'

  devise_for :users
  resources :foods do
    resources :orders
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :orders
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :food

  validates :quantity, numericality: { greater_than: 0 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
         has_many :orders, class_name: "Order"
         has_many :foods, through: :orders

  has_many :foods
  has_many :orders, through: :foods
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :role])
    end

    def user_not_authorized
      flash[:alert] = "You are not authorized to perform this action."
        # redirect_to root_path
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  # before_action :set_user_autorization
  before_action :set_user_autorization
  def index
    # authorize user
  end

  private

  def set_user_autorization
if current_user.admin == true
  action = params[:action]
else
  redirect_to foods_path, alert: "You are not authorized to perform this action."
 end
 end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def show
    @food = Food.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The food you were looking for could not be found."
    redirect_to foods_path
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food = current_user.foods.new(food_params)
    if @food.save
      redirect_to foods_path, notice: 'Food was successfully created.'
    else
      render :new
    end
end


  private

  def food_params
    params.require(:food).permit(:name, :description, :image, :price)
  end
end

app/controllers/menu_item_controller.rb
class MenuItemsController < ApplicationController
  before_action :set_menu_item, only: [:show, :edit, :update, :destroy]

  def index
    @menu_items = MenuItem.all
  end

  def show
  end

  def new
    @menu_item = MenuItem.new
  end

  def edit
  end

  def create
    @menu_item = MenuItem.new(menu_item_params)

    if @menu_item.save
      redirect_to @menu_item, notice: 'Menu item was successfully created.'
    else
      render :new
    end
  end

  def update
    if @menu_item.update(menu_item_params)
      redirect_to @menu_item, notice: 'Menu item was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @menu_item.destroy
    redirect_to menu_items_url, notice: 'Menu item was successfully destroyed.'
  end

  private
    def set_menu_item
      @menu_item = MenuItem.find(params[:id])
    end

    def menu_item_params
      params.require(:menu_item).permit(:name, :description, :price, :category_id, :image)
    end
end

app/controllers/order_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :update, :destroy]

  def index
    @orders = Order.all
    render json: @orders
  end

  def show
    render json: @order
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      render json: @order, status: :created
    else
      render json: @order.errors, status: :unprocessable_entity
    end
  end

  def update
    if @order.update(order_params)
      render json: @order
    else
      render json: @order.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @order.destroy
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:quantity, :ref_code, :total_price, :status, :user_id, :food_id)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: [:show, :update, :destroy]

  def index
    @orders = Order.all
    render json: @orders
  end

  def show
    render json: @order
  end

  def new
    @order = Order.new
  end

  def create
    food = Food.find(params[:food_id])
    @order = current_user.orders.build(order_params)
    @order.total_price *@order.quanitty if @order.quantity > 2

    if @order.save
      redirect_to foods_path, notice: "Your Food was successfully ordered"
    else
      render :new
    end
  end

  private

 def set_order
  @order = Order.find(params[:id])
 end
  def order_params
    params.require(:order).permit(:quantity, :food_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/dashboards/index.html.erb
<h1>Dashboards#index</h1>
<p>Find me in app/views/dashboards/index.html.erb</p>

app/views/foods/_form.html.erb
<%= form_with(model: @food) do |form| %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

   <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

   <div>
   <%= form.label :image, style: "display: block" %>
   <%= form.file_field :image %>
  </div><br/>

    <div>
      <%= form.label :price, style: "display: block" %>
      <%= form.text_field :price %>
    </div><br/>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/index.erb
<h1> Foods</h1>
<div class="foods">
  <% @foods.each do |food| %>
    <h3 class="name"><%= food.name %></h3>
    <li>
      <%= link_to food.name,food_path(food) %>
      </li>
  <%end%>
</div>

app/views/foods/index.html.erb
<h1> Foods</h1>
<div class="foods">
  <% @foods.each do |food| %>
    <h3 class="name"><%= food.name %></h3>
    <li>
      <%= link_to food.name,food_path(food) %>
      </li>
  <%end%>
</div>

app/views/foods/new.html.erb
<%= render "foods/form" %>

app/views/foods/order.html.erb
<h1>Order Food</h1>

<%= form_with(model: @food, local: true) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :description %>
  <%= form.text_area :description %>

  <%= form.label :image %>
  <%= form.text_field :image %>

  <%= form.label :price %>
  <%= form.number_field :price %>

  <%= form.submit %>
<% end %>

app/views/foods/show.html.erb
<h1>Food Item Details</h1>

<p>Name: <%= @food.name %></p>
<p>Description: <%= @food.description %></p>
<p>Price: <%= @food.price %></p>

  <%= link_to "Add to cart", new_food_order_path(food_id: @food), class: "btn btn-blue-500" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodDeliveryApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
        <% if user_signed_in? %>

        <div class="m-3 text-info">
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
          </div>
        <% else %>
        <%= link_to "Sign In", new_user_session_path %>
        <%= link_to "Sign up", new_user_registration_path%>
      <% end %>

      <div>
       <p class="notice"><%= notice %></p>
      </div>

      <div>
        <p class="alert"><%= alert %></p>
      </div>

    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: [@food, @order], url: food_orders_path, class: 'bg-white p-6 rounded-lg shadow-md') do |form| %>
  <div class="mb-4">
    <%= form.label :quantity, class: 'block text-gray-700 font-medium mb-2' %>
    <%= form.text_field :quantity, class: 'form-input py-2 px-3 text-gray-700 rounded-md' %>
  </div>
  <div class="text-center">
    <%= form.submit 'Submit',  class:"bg-amber-400 px-4 cursor-pointer rounded cursor font-bold" %>
  </div>
<% end %>

app/views/orders/new.html.erb
<%= render "orders/form" %>

app/views/orders/orders.html.erb
<%= form_with model: @order, local: true do |form| %>
  <%= form.label :customer_name %>
  <%= form.text_field :customer_name %>

  <%= form.label :customer_email %>
  <%= form.email_field :customer_email %>

  <%= form.label :customer_phone %>
  <%= form.tel_field :customer_phone %>

  <%= form.label :menu_items %>
  <% MenuItem.all.each do |menu_item| %>
    <div>
      <%= menu_item.name %>
      <%= form.number_field "menu_items[#{menu_item.id}]", min: 0 %>
    </div>
  <% end %>

  <%= form.submit %>
<% end %>

app/views/orders/show.html.erb
<h2>Order Details</h2>
<p>Quantity: <%= @order.quantity %></p>
<p>Food Name: <%= @order.food.name %></p>
<p>Food Total_Price: <%= @order.food.total_price %></p>